services:
  app:
    build:
      args:
        user: nasa
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: agriculture
    container_name: agriculture-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - 8888:8888
    environment:
      PYTHONPATH: /app
    volumes:
      - ./:/app
    networks:
      - agriculture
    user: root

  nginx:
    image: nginx:alpine
    container_name: agriculture-nginx
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - agriculture

networks:
  agriculture:
    driver: bridge